# agama url:   agama-builds/ci/prerelease/agama-ci-prerelease-{VERSION}/artifacts/linux/ubuntu/22.04
# master:      gfx-driver-builds/ci/master/gfx-driver-ci-master-{VERSION}/artifacts/Linux/Ubuntu/22.04/Release
# comp_igc:    gfx-driver-builds/ci/comp_igc/gfx-driver-ci-comp_igc-{VERSION}/artifacts/Linux/Ubuntu/22.04/ReleaseInternal
# dev_igc:     open-linux-driver-builds/ci/dev_igc/open-linux-driver-ci-dev_igc-{VERSION}/artifacts/linux/ubuntu/22.04"
# neo:         neo-builds/ci/embargo/ci-neo-{VERSION}/artifacts/Linux/Ubuntu/22.04/Release
# neo-master:  neo-builds/ci/master/ci-neo-master-{VERSION}/artifacts/linux/ubuntu/22.04
# neo-release: neo-builds/releases/releases_22.43/neo-releases-22.43.{VERSION}/artifacts/linux/ubuntu/22.04

variables:
  GFX_VERSION_LINUX_EMBARGO: gfx-driver-builds/ci/master/gfx-driver-ci-master-12953/artifacts/Linux/Ubuntu/22.04/Release
  GFX_VERSION_LINUX_INTERNAL: neo-builds/ci/master/ci-neo-master-025103/artifacts/linux/ubuntu/22.04
  GFX_VERSION_LINUX_PUBLIC: neo-builds/releases/releases_22.43/neo-releases-22.43.24595.35/artifacts/linux/ubuntu/22.04
  GFX_VERSION_LINUX_RELEASE: neo-builds/releases/releases_22.43/neo-releases-22.43.24595.35/artifacts/linux/ubuntu/20.04
  GFX_VERSION_WIN_INTERNAL: gfx-driver-builds/ci/master/gfx-driver-ci-master-12886/artifacts/Windows
  GFX_VERSION_WIN_PUBLIC: gfx-driver-builds/prod/releases_22ww49-ci-master-12886/prod-hini-releases_22ww49-ci-master-12886-revenue-pr-1014029/artifacts/Windows
  GFX_VERSION_WIN_RELEASE: gfx-driver-builds/prod/releases_22ww49-ci-master-12886/prod-hini-releases_22ww49-ci-master-12886-revenue-pr-1014029/artifacts/Windows
  DPCPP_VERSION_LINUX: sycl-nightly/20221214
  DPCPP_VERSION_WIN: sycl-nightly/20221214
