# CMake generated Testfile for 
# Source directory: C:/FlowSource/code/FlowLab/RayFlow/ext/glog
# Build directory: C:/FlowSource/code/FlowLab/RayFlow/ext/glog
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(logging_custom_prefix "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/Debug/logging_custom_prefix_unittest.exe")
  set_tests_properties(logging_custom_prefix PROPERTIES  SKIP_REGULAR_EXPRESSION "Check failed: time_ns within LogTimes::LOG_PERIOD_TOL_NS of LogTimes::LOG_PERIOD_NS" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;762;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(logging_custom_prefix "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/Release/logging_custom_prefix_unittest.exe")
  set_tests_properties(logging_custom_prefix PROPERTIES  SKIP_REGULAR_EXPRESSION "Check failed: time_ns within LogTimes::LOG_PERIOD_TOL_NS of LogTimes::LOG_PERIOD_NS" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;762;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(logging_custom_prefix "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/MinSizeRel/logging_custom_prefix_unittest.exe")
  set_tests_properties(logging_custom_prefix PROPERTIES  SKIP_REGULAR_EXPRESSION "Check failed: time_ns within LogTimes::LOG_PERIOD_TOL_NS of LogTimes::LOG_PERIOD_NS" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;762;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(logging_custom_prefix "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/RelWithDebInfo/logging_custom_prefix_unittest.exe")
  set_tests_properties(logging_custom_prefix PROPERTIES  SKIP_REGULAR_EXPRESSION "Check failed: time_ns within LogTimes::LOG_PERIOD_TOL_NS of LogTimes::LOG_PERIOD_NS" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;762;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
else()
  add_test(logging_custom_prefix NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(demangle "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/Debug/demangle_unittest.exe")
  set_tests_properties(demangle PROPERTIES  _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;843;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(demangle "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/Release/demangle_unittest.exe")
  set_tests_properties(demangle PROPERTIES  _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;843;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(demangle "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/MinSizeRel/demangle_unittest.exe")
  set_tests_properties(demangle PROPERTIES  _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;843;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(demangle "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/RelWithDebInfo/demangle_unittest.exe")
  set_tests_properties(demangle PROPERTIES  _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;843;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
else()
  add_test(demangle NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(logging "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/Debug/logging_unittest.exe")
  set_tests_properties(logging PROPERTIES  SKIP_REGULAR_EXPRESSION "Check failed: time_ns within LogTimes::LOG_PERIOD_TOL_NS of LogTimes::LOG_PERIOD_NS" TIMEOUT "30" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;844;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(logging "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/Release/logging_unittest.exe")
  set_tests_properties(logging PROPERTIES  SKIP_REGULAR_EXPRESSION "Check failed: time_ns within LogTimes::LOG_PERIOD_TOL_NS of LogTimes::LOG_PERIOD_NS" TIMEOUT "30" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;844;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(logging "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/MinSizeRel/logging_unittest.exe")
  set_tests_properties(logging PROPERTIES  SKIP_REGULAR_EXPRESSION "Check failed: time_ns within LogTimes::LOG_PERIOD_TOL_NS of LogTimes::LOG_PERIOD_NS" TIMEOUT "30" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;844;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(logging "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/RelWithDebInfo/logging_unittest.exe")
  set_tests_properties(logging PROPERTIES  SKIP_REGULAR_EXPRESSION "Check failed: time_ns within LogTimes::LOG_PERIOD_TOL_NS of LogTimes::LOG_PERIOD_NS" TIMEOUT "30" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;844;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
else()
  add_test(logging NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(signalhandler "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/Debug/signalhandler_unittest.exe")
  set_tests_properties(signalhandler PROPERTIES  _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;859;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(signalhandler "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/Release/signalhandler_unittest.exe")
  set_tests_properties(signalhandler PROPERTIES  _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;859;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(signalhandler "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/MinSizeRel/signalhandler_unittest.exe")
  set_tests_properties(signalhandler PROPERTIES  _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;859;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(signalhandler "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/RelWithDebInfo/signalhandler_unittest.exe")
  set_tests_properties(signalhandler PROPERTIES  _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;859;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
else()
  add_test(signalhandler NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(stacktrace "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/Debug/stacktrace_unittest.exe")
  set_tests_properties(stacktrace PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;863;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(stacktrace "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/Release/stacktrace_unittest.exe")
  set_tests_properties(stacktrace PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;863;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(stacktrace "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/MinSizeRel/stacktrace_unittest.exe")
  set_tests_properties(stacktrace PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;863;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(stacktrace "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/RelWithDebInfo/stacktrace_unittest.exe")
  set_tests_properties(stacktrace PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;863;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
else()
  add_test(stacktrace NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(stl_logging "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/Debug/stl_logging_unittest.exe")
  set_tests_properties(stl_logging PROPERTIES  _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;867;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(stl_logging "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/Release/stl_logging_unittest.exe")
  set_tests_properties(stl_logging PROPERTIES  _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;867;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(stl_logging "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/MinSizeRel/stl_logging_unittest.exe")
  set_tests_properties(stl_logging PROPERTIES  _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;867;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(stl_logging "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/RelWithDebInfo/stl_logging_unittest.exe")
  set_tests_properties(stl_logging PROPERTIES  _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;867;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
else()
  add_test(stl_logging NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(symbolize "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/Debug/symbolize_unittest.exe")
  set_tests_properties(symbolize PROPERTIES  _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;870;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(symbolize "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/Release/symbolize_unittest.exe")
  set_tests_properties(symbolize PROPERTIES  _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;870;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(symbolize "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/MinSizeRel/symbolize_unittest.exe")
  set_tests_properties(symbolize PROPERTIES  _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;870;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(symbolize "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/RelWithDebInfo/symbolize_unittest.exe")
  set_tests_properties(symbolize PROPERTIES  _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;870;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
else()
  add_test(symbolize NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(mock-log "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/Debug/mock-log_unittest.exe")
  set_tests_properties(mock-log PROPERTIES  _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;881;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(mock-log "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/Release/mock-log_unittest.exe")
  set_tests_properties(mock-log PROPERTIES  _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;881;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(mock-log "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/MinSizeRel/mock-log_unittest.exe")
  set_tests_properties(mock-log PROPERTIES  _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;881;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(mock-log "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/RelWithDebInfo/mock-log_unittest.exe")
  set_tests_properties(mock-log PROPERTIES  _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;881;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
else()
  add_test(mock-log NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(cmake_package_config_init "C:/Program Files/CMake/bin/cmake.exe" "-DTEST_BINARY_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config" "-DINITIAL_CACHE=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config/glog_package_config_initial_cache.cmake" "-DCACHEVARS=set (BUILD_SHARED_LIBS ON CACHE BOOL \"Build shared libraries\")
set (BUILD_TESTING ON CACHE BOOL \"Build the testing tree.\")
set (CMAKE_AR \"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/lib.exe\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_AR \"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/lib.exe\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_CONFIGURATION_TYPES \"Debug;Release;MinSizeRel;RelWithDebInfo\" CACHE STRING \"Semicolon separated list of supported configuration types, only supports Debug, Release, MinSizeRel, and RelWithDebInfo, anything else will be ignored.\")
set (CMAKE_CXX_FLAGS \"/DWIN32 /D_WINDOWS /GR /EHsc\" CACHE STRING \"Flags used by the CXX compiler during all build types.\")
set (CMAKE_CXX_FLAGS_DEBUG \"/Zi /Ob0 /Od /RTC1\" CACHE STRING \"Flags used by the CXX compiler during DEBUG builds.\")
set (CMAKE_CXX_FLAGS_MINSIZEREL \"/O1 /Ob1 /DNDEBUG\" CACHE STRING \"Flags used by the CXX compiler during MINSIZEREL builds.\")
set (CMAKE_CXX_FLAGS_RELEASE \"/O2 /Ob2 /DNDEBUG\" CACHE STRING \"Flags used by the CXX compiler during RELEASE builds.\")
set (CMAKE_CXX_FLAGS_RELWITHDEBINFO \"/Zi /O2 /Ob1 /DNDEBUG\" CACHE STRING \"Flags used by the CXX compiler during RELWITHDEBINFO builds.\")
set (CMAKE_CXX_STANDARD_LIBRARIES \"kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib\" CACHE STRING \"Libraries linked by default with all C++ applications.\")
set (CMAKE_EXE_LINKER_FLAGS \"/machine:x64\" CACHE STRING \"Flags used by the linker during all build types.\")
set (CMAKE_EXE_LINKER_FLAGS_DEBUG \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during DEBUG builds.\")
set (CMAKE_EXE_LINKER_FLAGS_MINSIZEREL \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during MINSIZEREL builds.\")
set (CMAKE_EXE_LINKER_FLAGS_RELEASE \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during RELEASE builds.\")
set (CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during RELWITHDEBINFO builds.\")
set (CMAKE_INSTALL_BINDIR \"bin\" CACHE PATH \"User executables (bin)\")
set (CMAKE_INSTALL_DATAROOTDIR \"share\" CACHE PATH \"Read-only architecture-independent data root (share)\")
set (CMAKE_INSTALL_INCLUDEDIR \"include\" CACHE PATH \"C header files (include)\")
set (CMAKE_INSTALL_LIBDIR \"lib\" CACHE PATH \"Object code libraries (lib)\")
set (CMAKE_INSTALL_LIBEXECDIR \"libexec\" CACHE PATH \"Program executables (libexec)\")
set (CMAKE_INSTALL_LOCALSTATEDIR \"var\" CACHE PATH \"Modifiable single-machine data (var)\")
set (CMAKE_INSTALL_OLDINCLUDEDIR \"/usr/include\" CACHE PATH \"C header files for non-gcc (/usr/include)\")
set (CMAKE_INSTALL_PREFIX \"C:/Program Files (x86)/glog\" CACHE PATH \"Install path prefix, prepended onto install directories.\")
set (CMAKE_INSTALL_SBINDIR \"sbin\" CACHE PATH \"System admin executables (sbin)\")
set (CMAKE_INSTALL_SHAREDSTATEDIR \"com\" CACHE PATH \"Modifiable architecture-independent data (com)\")
set (CMAKE_INSTALL_SYSCONFDIR \"etc\" CACHE PATH \"Read-only single-machine data (etc)\")
set (CMAKE_LINKER \"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/link.exe\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_LINKER \"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/link.exe\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_MODULE_LINKER_FLAGS \"/machine:x64\" CACHE STRING \"Flags used by the linker during the creation of modules during all build types.\")
set (CMAKE_MODULE_LINKER_FLAGS_DEBUG \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during the creation of modules during DEBUG builds.\")
set (CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during the creation of modules during MINSIZEREL builds.\")
set (CMAKE_MODULE_LINKER_FLAGS_RELEASE \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during the creation of modules during RELEASE builds.\")
set (CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during the creation of modules during RELWITHDEBINFO builds.\")
set (CMAKE_MT \"CMAKE_MT-NOTFOUND\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_MT \"CMAKE_MT-NOTFOUND\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_RC_COMPILER \"rc\" CACHE FILEPATH \"RC compiler\")
set (CMAKE_RC_COMPILER \"rc\" CACHE FILEPATH \"RC compiler\")
set (CMAKE_RC_FLAGS \"-DWIN32\" CACHE STRING \"Flags for Windows Resource Compiler during all build types.\")
set (CMAKE_RC_FLAGS_DEBUG \"-D_DEBUG\" CACHE STRING \"Flags for Windows Resource Compiler during DEBUG builds.\")
set (CMAKE_SHARED_LINKER_FLAGS \"/machine:x64\" CACHE STRING \"Flags used by the linker during the creation of shared libraries during all build types.\")
set (CMAKE_SHARED_LINKER_FLAGS_DEBUG \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during the creation of shared libraries during DEBUG builds.\")
set (CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during the creation of shared libraries during MINSIZEREL builds.\")
set (CMAKE_SHARED_LINKER_FLAGS_RELEASE \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during the creation of shared libraries during RELEASE builds.\")
set (CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during the creation of shared libraries during RELWITHDEBINFO builds.\")
set (CMAKE_SKIP_INSTALL_RPATH NO CACHE BOOL \"If set, runtime paths are not added when installing shared libraries, but are added when building.\")
set (CMAKE_SKIP_RPATH NO CACHE BOOL \"If set, runtime paths are not added when using shared libraries.\")
set (CMAKE_STATIC_LINKER_FLAGS \"/machine:x64\" CACHE STRING \"Flags used by the linker during the creation of static libraries during all build types.\")
set (CMAKE_VERBOSE_MAKEFILE FALSE CACHE BOOL \"If this value is on, makefiles will be generated without the .SILENT directive, and all commands will be echoed to the console during the make.  This is useful for debugging only. With Visual Studio IDE projects all commands are done without /nologo.\")
set (COVERAGE_COMMAND \"COVERAGE_COMMAND-NOTFOUND\" CACHE FILEPATH \"Path to the coverage program that CTest uses for performing coverage inspection\")
set (COVERAGE_EXTRA_FLAGS \"-l\" CACHE STRING \"Extra command line flags to pass to the coverage tool\")
set (CPACK_BINARY_7Z OFF CACHE BOOL \"Enable to build 7-Zip packages\")
set (CPACK_BINARY_IFW OFF CACHE BOOL \"Enable to build IFW packages\")
set (CPACK_BINARY_NSIS ON CACHE BOOL \"Enable to build NSIS packages\")
set (CPACK_BINARY_NUGET OFF CACHE BOOL \"Enable to build NuGet packages\")
set (CPACK_BINARY_WIX OFF CACHE BOOL \"Enable to build WiX packages\")
set (CPACK_BINARY_ZIP OFF CACHE BOOL \"Enable to build ZIP packages\")
set (CPACK_SOURCE_7Z ON CACHE BOOL \"Enable to build 7-Zip source packages\")
set (CPACK_SOURCE_ZIP ON CACHE BOOL \"Enable to build ZIP source packages\")
set (CTEST_SUBMIT_RETRY_COUNT \"3\" CACHE STRING \"How many times to retry timed-out CTest submissions.\")
set (CTEST_SUBMIT_RETRY_DELAY \"5\" CACHE STRING \"How long to wait between timed-out CTest submissions.\")
set (DART_TESTING_TIMEOUT \"1500\" CACHE STRING \"Maximum time allowed before CTest will kill the test.\")
set (GTest_DIR \"C:/ProgramData/Anaconda3/Library/lib/cmake/GTest\" CACHE PATH \"The directory containing a CMake configuration file for GTest.\")
set (MAKECOMMAND \"\\\"C:\\\\1rogram Files\\\\1Make\\\\1in\\\\1make.exe\\\" --build . --config \\\"\${CTEST_CONFIGURATION_TYPE}\\\"\" CACHE STRING \"Command to build the project\")
set (MEMORYCHECK_COMMAND \"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.6/bin/cuda-memcheck.exe\" CACHE FILEPATH \"Path to the memory checking command, used for memory error detection.\")
set (PRINT_UNSYMBOLIZED_STACK_TRACES OFF CACHE BOOL \"Print file offsets in traces instead of symbolizing\")
set (SITE \"Flow\" CACHE STRING \"Name of the computer/site where compile is being run\")
set (Unwind_INCLUDE_DIR \"Unwind_INCLUDE_DIR-NOTFOUND\" CACHE PATH \"unwind include directory\")
set (Unwind_LIBRARY \"Unwind_LIBRARY-NOTFOUND\" CACHE FILEPATH \"unwind library\")
set (WITH_CUSTOM_PREFIX ON CACHE BOOL \"Enable support for user-generated message prefixes\")
set (WITH_GFLAGS ON CACHE BOOL \"Use gflags\")
set (WITH_GMOCK ON CACHE BOOL \"Use Google Mock\")
set (WITH_GTEST ON CACHE BOOL \"Use Google Test\")
set (WITH_PKGCONFIG ON CACHE BOOL \"Enable pkg-config support\")
set (WITH_SYMBOLIZE ON CACHE BOOL \"Enable symbolize module\")
set (WITH_THREADS ON CACHE BOOL \"Enable multithreading support\")
set (WITH_TLS ON CACHE BOOL \"Enable Thread Local Storage (TLS) support\")
set (WITH_UNWIND ON CACHE BOOL \"Enable libunwind support\")
set (gflags_DIR \"gflags_DIR-NOTFOUND\" CACHE PATH \"The directory containing a CMake configuration file for gflags.\")
" "-P" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cmake/TestInitPackageConfig.cmake")
  set_tests_properties(cmake_package_config_init PROPERTIES  FIXTURES_SETUP "cmake_package_config" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;893;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(cmake_package_config_init "C:/Program Files/CMake/bin/cmake.exe" "-DTEST_BINARY_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config" "-DINITIAL_CACHE=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config/glog_package_config_initial_cache.cmake" "-DCACHEVARS=set (BUILD_SHARED_LIBS ON CACHE BOOL \"Build shared libraries\")
set (BUILD_TESTING ON CACHE BOOL \"Build the testing tree.\")
set (CMAKE_AR \"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/lib.exe\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_AR \"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/lib.exe\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_CONFIGURATION_TYPES \"Debug;Release;MinSizeRel;RelWithDebInfo\" CACHE STRING \"Semicolon separated list of supported configuration types, only supports Debug, Release, MinSizeRel, and RelWithDebInfo, anything else will be ignored.\")
set (CMAKE_CXX_FLAGS \"/DWIN32 /D_WINDOWS /GR /EHsc\" CACHE STRING \"Flags used by the CXX compiler during all build types.\")
set (CMAKE_CXX_FLAGS_DEBUG \"/Zi /Ob0 /Od /RTC1\" CACHE STRING \"Flags used by the CXX compiler during DEBUG builds.\")
set (CMAKE_CXX_FLAGS_MINSIZEREL \"/O1 /Ob1 /DNDEBUG\" CACHE STRING \"Flags used by the CXX compiler during MINSIZEREL builds.\")
set (CMAKE_CXX_FLAGS_RELEASE \"/O2 /Ob2 /DNDEBUG\" CACHE STRING \"Flags used by the CXX compiler during RELEASE builds.\")
set (CMAKE_CXX_FLAGS_RELWITHDEBINFO \"/Zi /O2 /Ob1 /DNDEBUG\" CACHE STRING \"Flags used by the CXX compiler during RELWITHDEBINFO builds.\")
set (CMAKE_CXX_STANDARD_LIBRARIES \"kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib\" CACHE STRING \"Libraries linked by default with all C++ applications.\")
set (CMAKE_EXE_LINKER_FLAGS \"/machine:x64\" CACHE STRING \"Flags used by the linker during all build types.\")
set (CMAKE_EXE_LINKER_FLAGS_DEBUG \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during DEBUG builds.\")
set (CMAKE_EXE_LINKER_FLAGS_MINSIZEREL \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during MINSIZEREL builds.\")
set (CMAKE_EXE_LINKER_FLAGS_RELEASE \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during RELEASE builds.\")
set (CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during RELWITHDEBINFO builds.\")
set (CMAKE_INSTALL_BINDIR \"bin\" CACHE PATH \"User executables (bin)\")
set (CMAKE_INSTALL_DATAROOTDIR \"share\" CACHE PATH \"Read-only architecture-independent data root (share)\")
set (CMAKE_INSTALL_INCLUDEDIR \"include\" CACHE PATH \"C header files (include)\")
set (CMAKE_INSTALL_LIBDIR \"lib\" CACHE PATH \"Object code libraries (lib)\")
set (CMAKE_INSTALL_LIBEXECDIR \"libexec\" CACHE PATH \"Program executables (libexec)\")
set (CMAKE_INSTALL_LOCALSTATEDIR \"var\" CACHE PATH \"Modifiable single-machine data (var)\")
set (CMAKE_INSTALL_OLDINCLUDEDIR \"/usr/include\" CACHE PATH \"C header files for non-gcc (/usr/include)\")
set (CMAKE_INSTALL_PREFIX \"C:/Program Files (x86)/glog\" CACHE PATH \"Install path prefix, prepended onto install directories.\")
set (CMAKE_INSTALL_SBINDIR \"sbin\" CACHE PATH \"System admin executables (sbin)\")
set (CMAKE_INSTALL_SHAREDSTATEDIR \"com\" CACHE PATH \"Modifiable architecture-independent data (com)\")
set (CMAKE_INSTALL_SYSCONFDIR \"etc\" CACHE PATH \"Read-only single-machine data (etc)\")
set (CMAKE_LINKER \"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/link.exe\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_LINKER \"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/link.exe\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_MODULE_LINKER_FLAGS \"/machine:x64\" CACHE STRING \"Flags used by the linker during the creation of modules during all build types.\")
set (CMAKE_MODULE_LINKER_FLAGS_DEBUG \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during the creation of modules during DEBUG builds.\")
set (CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during the creation of modules during MINSIZEREL builds.\")
set (CMAKE_MODULE_LINKER_FLAGS_RELEASE \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during the creation of modules during RELEASE builds.\")
set (CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during the creation of modules during RELWITHDEBINFO builds.\")
set (CMAKE_MT \"CMAKE_MT-NOTFOUND\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_MT \"CMAKE_MT-NOTFOUND\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_RC_COMPILER \"rc\" CACHE FILEPATH \"RC compiler\")
set (CMAKE_RC_COMPILER \"rc\" CACHE FILEPATH \"RC compiler\")
set (CMAKE_RC_FLAGS \"-DWIN32\" CACHE STRING \"Flags for Windows Resource Compiler during all build types.\")
set (CMAKE_RC_FLAGS_DEBUG \"-D_DEBUG\" CACHE STRING \"Flags for Windows Resource Compiler during DEBUG builds.\")
set (CMAKE_SHARED_LINKER_FLAGS \"/machine:x64\" CACHE STRING \"Flags used by the linker during the creation of shared libraries during all build types.\")
set (CMAKE_SHARED_LINKER_FLAGS_DEBUG \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during the creation of shared libraries during DEBUG builds.\")
set (CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during the creation of shared libraries during MINSIZEREL builds.\")
set (CMAKE_SHARED_LINKER_FLAGS_RELEASE \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during the creation of shared libraries during RELEASE builds.\")
set (CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during the creation of shared libraries during RELWITHDEBINFO builds.\")
set (CMAKE_SKIP_INSTALL_RPATH NO CACHE BOOL \"If set, runtime paths are not added when installing shared libraries, but are added when building.\")
set (CMAKE_SKIP_RPATH NO CACHE BOOL \"If set, runtime paths are not added when using shared libraries.\")
set (CMAKE_STATIC_LINKER_FLAGS \"/machine:x64\" CACHE STRING \"Flags used by the linker during the creation of static libraries during all build types.\")
set (CMAKE_VERBOSE_MAKEFILE FALSE CACHE BOOL \"If this value is on, makefiles will be generated without the .SILENT directive, and all commands will be echoed to the console during the make.  This is useful for debugging only. With Visual Studio IDE projects all commands are done without /nologo.\")
set (COVERAGE_COMMAND \"COVERAGE_COMMAND-NOTFOUND\" CACHE FILEPATH \"Path to the coverage program that CTest uses for performing coverage inspection\")
set (COVERAGE_EXTRA_FLAGS \"-l\" CACHE STRING \"Extra command line flags to pass to the coverage tool\")
set (CPACK_BINARY_7Z OFF CACHE BOOL \"Enable to build 7-Zip packages\")
set (CPACK_BINARY_IFW OFF CACHE BOOL \"Enable to build IFW packages\")
set (CPACK_BINARY_NSIS ON CACHE BOOL \"Enable to build NSIS packages\")
set (CPACK_BINARY_NUGET OFF CACHE BOOL \"Enable to build NuGet packages\")
set (CPACK_BINARY_WIX OFF CACHE BOOL \"Enable to build WiX packages\")
set (CPACK_BINARY_ZIP OFF CACHE BOOL \"Enable to build ZIP packages\")
set (CPACK_SOURCE_7Z ON CACHE BOOL \"Enable to build 7-Zip source packages\")
set (CPACK_SOURCE_ZIP ON CACHE BOOL \"Enable to build ZIP source packages\")
set (CTEST_SUBMIT_RETRY_COUNT \"3\" CACHE STRING \"How many times to retry timed-out CTest submissions.\")
set (CTEST_SUBMIT_RETRY_DELAY \"5\" CACHE STRING \"How long to wait between timed-out CTest submissions.\")
set (DART_TESTING_TIMEOUT \"1500\" CACHE STRING \"Maximum time allowed before CTest will kill the test.\")
set (GTest_DIR \"C:/ProgramData/Anaconda3/Library/lib/cmake/GTest\" CACHE PATH \"The directory containing a CMake configuration file for GTest.\")
set (MAKECOMMAND \"\\\"C:\\\\1rogram Files\\\\1Make\\\\1in\\\\1make.exe\\\" --build . --config \\\"\${CTEST_CONFIGURATION_TYPE}\\\"\" CACHE STRING \"Command to build the project\")
set (MEMORYCHECK_COMMAND \"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.6/bin/cuda-memcheck.exe\" CACHE FILEPATH \"Path to the memory checking command, used for memory error detection.\")
set (PRINT_UNSYMBOLIZED_STACK_TRACES OFF CACHE BOOL \"Print file offsets in traces instead of symbolizing\")
set (SITE \"Flow\" CACHE STRING \"Name of the computer/site where compile is being run\")
set (Unwind_INCLUDE_DIR \"Unwind_INCLUDE_DIR-NOTFOUND\" CACHE PATH \"unwind include directory\")
set (Unwind_LIBRARY \"Unwind_LIBRARY-NOTFOUND\" CACHE FILEPATH \"unwind library\")
set (WITH_CUSTOM_PREFIX ON CACHE BOOL \"Enable support for user-generated message prefixes\")
set (WITH_GFLAGS ON CACHE BOOL \"Use gflags\")
set (WITH_GMOCK ON CACHE BOOL \"Use Google Mock\")
set (WITH_GTEST ON CACHE BOOL \"Use Google Test\")
set (WITH_PKGCONFIG ON CACHE BOOL \"Enable pkg-config support\")
set (WITH_SYMBOLIZE ON CACHE BOOL \"Enable symbolize module\")
set (WITH_THREADS ON CACHE BOOL \"Enable multithreading support\")
set (WITH_TLS ON CACHE BOOL \"Enable Thread Local Storage (TLS) support\")
set (WITH_UNWIND ON CACHE BOOL \"Enable libunwind support\")
set (gflags_DIR \"gflags_DIR-NOTFOUND\" CACHE PATH \"The directory containing a CMake configuration file for gflags.\")
" "-P" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cmake/TestInitPackageConfig.cmake")
  set_tests_properties(cmake_package_config_init PROPERTIES  FIXTURES_SETUP "cmake_package_config" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;893;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(cmake_package_config_init "C:/Program Files/CMake/bin/cmake.exe" "-DTEST_BINARY_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config" "-DINITIAL_CACHE=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config/glog_package_config_initial_cache.cmake" "-DCACHEVARS=set (BUILD_SHARED_LIBS ON CACHE BOOL \"Build shared libraries\")
set (BUILD_TESTING ON CACHE BOOL \"Build the testing tree.\")
set (CMAKE_AR \"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/lib.exe\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_AR \"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/lib.exe\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_CONFIGURATION_TYPES \"Debug;Release;MinSizeRel;RelWithDebInfo\" CACHE STRING \"Semicolon separated list of supported configuration types, only supports Debug, Release, MinSizeRel, and RelWithDebInfo, anything else will be ignored.\")
set (CMAKE_CXX_FLAGS \"/DWIN32 /D_WINDOWS /GR /EHsc\" CACHE STRING \"Flags used by the CXX compiler during all build types.\")
set (CMAKE_CXX_FLAGS_DEBUG \"/Zi /Ob0 /Od /RTC1\" CACHE STRING \"Flags used by the CXX compiler during DEBUG builds.\")
set (CMAKE_CXX_FLAGS_MINSIZEREL \"/O1 /Ob1 /DNDEBUG\" CACHE STRING \"Flags used by the CXX compiler during MINSIZEREL builds.\")
set (CMAKE_CXX_FLAGS_RELEASE \"/O2 /Ob2 /DNDEBUG\" CACHE STRING \"Flags used by the CXX compiler during RELEASE builds.\")
set (CMAKE_CXX_FLAGS_RELWITHDEBINFO \"/Zi /O2 /Ob1 /DNDEBUG\" CACHE STRING \"Flags used by the CXX compiler during RELWITHDEBINFO builds.\")
set (CMAKE_CXX_STANDARD_LIBRARIES \"kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib\" CACHE STRING \"Libraries linked by default with all C++ applications.\")
set (CMAKE_EXE_LINKER_FLAGS \"/machine:x64\" CACHE STRING \"Flags used by the linker during all build types.\")
set (CMAKE_EXE_LINKER_FLAGS_DEBUG \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during DEBUG builds.\")
set (CMAKE_EXE_LINKER_FLAGS_MINSIZEREL \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during MINSIZEREL builds.\")
set (CMAKE_EXE_LINKER_FLAGS_RELEASE \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during RELEASE builds.\")
set (CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during RELWITHDEBINFO builds.\")
set (CMAKE_INSTALL_BINDIR \"bin\" CACHE PATH \"User executables (bin)\")
set (CMAKE_INSTALL_DATAROOTDIR \"share\" CACHE PATH \"Read-only architecture-independent data root (share)\")
set (CMAKE_INSTALL_INCLUDEDIR \"include\" CACHE PATH \"C header files (include)\")
set (CMAKE_INSTALL_LIBDIR \"lib\" CACHE PATH \"Object code libraries (lib)\")
set (CMAKE_INSTALL_LIBEXECDIR \"libexec\" CACHE PATH \"Program executables (libexec)\")
set (CMAKE_INSTALL_LOCALSTATEDIR \"var\" CACHE PATH \"Modifiable single-machine data (var)\")
set (CMAKE_INSTALL_OLDINCLUDEDIR \"/usr/include\" CACHE PATH \"C header files for non-gcc (/usr/include)\")
set (CMAKE_INSTALL_PREFIX \"C:/Program Files (x86)/glog\" CACHE PATH \"Install path prefix, prepended onto install directories.\")
set (CMAKE_INSTALL_SBINDIR \"sbin\" CACHE PATH \"System admin executables (sbin)\")
set (CMAKE_INSTALL_SHAREDSTATEDIR \"com\" CACHE PATH \"Modifiable architecture-independent data (com)\")
set (CMAKE_INSTALL_SYSCONFDIR \"etc\" CACHE PATH \"Read-only single-machine data (etc)\")
set (CMAKE_LINKER \"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/link.exe\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_LINKER \"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/link.exe\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_MODULE_LINKER_FLAGS \"/machine:x64\" CACHE STRING \"Flags used by the linker during the creation of modules during all build types.\")
set (CMAKE_MODULE_LINKER_FLAGS_DEBUG \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during the creation of modules during DEBUG builds.\")
set (CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during the creation of modules during MINSIZEREL builds.\")
set (CMAKE_MODULE_LINKER_FLAGS_RELEASE \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during the creation of modules during RELEASE builds.\")
set (CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during the creation of modules during RELWITHDEBINFO builds.\")
set (CMAKE_MT \"CMAKE_MT-NOTFOUND\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_MT \"CMAKE_MT-NOTFOUND\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_RC_COMPILER \"rc\" CACHE FILEPATH \"RC compiler\")
set (CMAKE_RC_COMPILER \"rc\" CACHE FILEPATH \"RC compiler\")
set (CMAKE_RC_FLAGS \"-DWIN32\" CACHE STRING \"Flags for Windows Resource Compiler during all build types.\")
set (CMAKE_RC_FLAGS_DEBUG \"-D_DEBUG\" CACHE STRING \"Flags for Windows Resource Compiler during DEBUG builds.\")
set (CMAKE_SHARED_LINKER_FLAGS \"/machine:x64\" CACHE STRING \"Flags used by the linker during the creation of shared libraries during all build types.\")
set (CMAKE_SHARED_LINKER_FLAGS_DEBUG \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during the creation of shared libraries during DEBUG builds.\")
set (CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during the creation of shared libraries during MINSIZEREL builds.\")
set (CMAKE_SHARED_LINKER_FLAGS_RELEASE \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during the creation of shared libraries during RELEASE builds.\")
set (CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during the creation of shared libraries during RELWITHDEBINFO builds.\")
set (CMAKE_SKIP_INSTALL_RPATH NO CACHE BOOL \"If set, runtime paths are not added when installing shared libraries, but are added when building.\")
set (CMAKE_SKIP_RPATH NO CACHE BOOL \"If set, runtime paths are not added when using shared libraries.\")
set (CMAKE_STATIC_LINKER_FLAGS \"/machine:x64\" CACHE STRING \"Flags used by the linker during the creation of static libraries during all build types.\")
set (CMAKE_VERBOSE_MAKEFILE FALSE CACHE BOOL \"If this value is on, makefiles will be generated without the .SILENT directive, and all commands will be echoed to the console during the make.  This is useful for debugging only. With Visual Studio IDE projects all commands are done without /nologo.\")
set (COVERAGE_COMMAND \"COVERAGE_COMMAND-NOTFOUND\" CACHE FILEPATH \"Path to the coverage program that CTest uses for performing coverage inspection\")
set (COVERAGE_EXTRA_FLAGS \"-l\" CACHE STRING \"Extra command line flags to pass to the coverage tool\")
set (CPACK_BINARY_7Z OFF CACHE BOOL \"Enable to build 7-Zip packages\")
set (CPACK_BINARY_IFW OFF CACHE BOOL \"Enable to build IFW packages\")
set (CPACK_BINARY_NSIS ON CACHE BOOL \"Enable to build NSIS packages\")
set (CPACK_BINARY_NUGET OFF CACHE BOOL \"Enable to build NuGet packages\")
set (CPACK_BINARY_WIX OFF CACHE BOOL \"Enable to build WiX packages\")
set (CPACK_BINARY_ZIP OFF CACHE BOOL \"Enable to build ZIP packages\")
set (CPACK_SOURCE_7Z ON CACHE BOOL \"Enable to build 7-Zip source packages\")
set (CPACK_SOURCE_ZIP ON CACHE BOOL \"Enable to build ZIP source packages\")
set (CTEST_SUBMIT_RETRY_COUNT \"3\" CACHE STRING \"How many times to retry timed-out CTest submissions.\")
set (CTEST_SUBMIT_RETRY_DELAY \"5\" CACHE STRING \"How long to wait between timed-out CTest submissions.\")
set (DART_TESTING_TIMEOUT \"1500\" CACHE STRING \"Maximum time allowed before CTest will kill the test.\")
set (GTest_DIR \"C:/ProgramData/Anaconda3/Library/lib/cmake/GTest\" CACHE PATH \"The directory containing a CMake configuration file for GTest.\")
set (MAKECOMMAND \"\\\"C:\\\\1rogram Files\\\\1Make\\\\1in\\\\1make.exe\\\" --build . --config \\\"\${CTEST_CONFIGURATION_TYPE}\\\"\" CACHE STRING \"Command to build the project\")
set (MEMORYCHECK_COMMAND \"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.6/bin/cuda-memcheck.exe\" CACHE FILEPATH \"Path to the memory checking command, used for memory error detection.\")
set (PRINT_UNSYMBOLIZED_STACK_TRACES OFF CACHE BOOL \"Print file offsets in traces instead of symbolizing\")
set (SITE \"Flow\" CACHE STRING \"Name of the computer/site where compile is being run\")
set (Unwind_INCLUDE_DIR \"Unwind_INCLUDE_DIR-NOTFOUND\" CACHE PATH \"unwind include directory\")
set (Unwind_LIBRARY \"Unwind_LIBRARY-NOTFOUND\" CACHE FILEPATH \"unwind library\")
set (WITH_CUSTOM_PREFIX ON CACHE BOOL \"Enable support for user-generated message prefixes\")
set (WITH_GFLAGS ON CACHE BOOL \"Use gflags\")
set (WITH_GMOCK ON CACHE BOOL \"Use Google Mock\")
set (WITH_GTEST ON CACHE BOOL \"Use Google Test\")
set (WITH_PKGCONFIG ON CACHE BOOL \"Enable pkg-config support\")
set (WITH_SYMBOLIZE ON CACHE BOOL \"Enable symbolize module\")
set (WITH_THREADS ON CACHE BOOL \"Enable multithreading support\")
set (WITH_TLS ON CACHE BOOL \"Enable Thread Local Storage (TLS) support\")
set (WITH_UNWIND ON CACHE BOOL \"Enable libunwind support\")
set (gflags_DIR \"gflags_DIR-NOTFOUND\" CACHE PATH \"The directory containing a CMake configuration file for gflags.\")
" "-P" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cmake/TestInitPackageConfig.cmake")
  set_tests_properties(cmake_package_config_init PROPERTIES  FIXTURES_SETUP "cmake_package_config" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;893;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(cmake_package_config_init "C:/Program Files/CMake/bin/cmake.exe" "-DTEST_BINARY_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config" "-DINITIAL_CACHE=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config/glog_package_config_initial_cache.cmake" "-DCACHEVARS=set (BUILD_SHARED_LIBS ON CACHE BOOL \"Build shared libraries\")
set (BUILD_TESTING ON CACHE BOOL \"Build the testing tree.\")
set (CMAKE_AR \"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/lib.exe\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_AR \"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/lib.exe\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_CONFIGURATION_TYPES \"Debug;Release;MinSizeRel;RelWithDebInfo\" CACHE STRING \"Semicolon separated list of supported configuration types, only supports Debug, Release, MinSizeRel, and RelWithDebInfo, anything else will be ignored.\")
set (CMAKE_CXX_FLAGS \"/DWIN32 /D_WINDOWS /GR /EHsc\" CACHE STRING \"Flags used by the CXX compiler during all build types.\")
set (CMAKE_CXX_FLAGS_DEBUG \"/Zi /Ob0 /Od /RTC1\" CACHE STRING \"Flags used by the CXX compiler during DEBUG builds.\")
set (CMAKE_CXX_FLAGS_MINSIZEREL \"/O1 /Ob1 /DNDEBUG\" CACHE STRING \"Flags used by the CXX compiler during MINSIZEREL builds.\")
set (CMAKE_CXX_FLAGS_RELEASE \"/O2 /Ob2 /DNDEBUG\" CACHE STRING \"Flags used by the CXX compiler during RELEASE builds.\")
set (CMAKE_CXX_FLAGS_RELWITHDEBINFO \"/Zi /O2 /Ob1 /DNDEBUG\" CACHE STRING \"Flags used by the CXX compiler during RELWITHDEBINFO builds.\")
set (CMAKE_CXX_STANDARD_LIBRARIES \"kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib\" CACHE STRING \"Libraries linked by default with all C++ applications.\")
set (CMAKE_EXE_LINKER_FLAGS \"/machine:x64\" CACHE STRING \"Flags used by the linker during all build types.\")
set (CMAKE_EXE_LINKER_FLAGS_DEBUG \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during DEBUG builds.\")
set (CMAKE_EXE_LINKER_FLAGS_MINSIZEREL \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during MINSIZEREL builds.\")
set (CMAKE_EXE_LINKER_FLAGS_RELEASE \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during RELEASE builds.\")
set (CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during RELWITHDEBINFO builds.\")
set (CMAKE_INSTALL_BINDIR \"bin\" CACHE PATH \"User executables (bin)\")
set (CMAKE_INSTALL_DATAROOTDIR \"share\" CACHE PATH \"Read-only architecture-independent data root (share)\")
set (CMAKE_INSTALL_INCLUDEDIR \"include\" CACHE PATH \"C header files (include)\")
set (CMAKE_INSTALL_LIBDIR \"lib\" CACHE PATH \"Object code libraries (lib)\")
set (CMAKE_INSTALL_LIBEXECDIR \"libexec\" CACHE PATH \"Program executables (libexec)\")
set (CMAKE_INSTALL_LOCALSTATEDIR \"var\" CACHE PATH \"Modifiable single-machine data (var)\")
set (CMAKE_INSTALL_OLDINCLUDEDIR \"/usr/include\" CACHE PATH \"C header files for non-gcc (/usr/include)\")
set (CMAKE_INSTALL_PREFIX \"C:/Program Files (x86)/glog\" CACHE PATH \"Install path prefix, prepended onto install directories.\")
set (CMAKE_INSTALL_SBINDIR \"sbin\" CACHE PATH \"System admin executables (sbin)\")
set (CMAKE_INSTALL_SHAREDSTATEDIR \"com\" CACHE PATH \"Modifiable architecture-independent data (com)\")
set (CMAKE_INSTALL_SYSCONFDIR \"etc\" CACHE PATH \"Read-only single-machine data (etc)\")
set (CMAKE_LINKER \"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/link.exe\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_LINKER \"C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/link.exe\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_MODULE_LINKER_FLAGS \"/machine:x64\" CACHE STRING \"Flags used by the linker during the creation of modules during all build types.\")
set (CMAKE_MODULE_LINKER_FLAGS_DEBUG \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during the creation of modules during DEBUG builds.\")
set (CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during the creation of modules during MINSIZEREL builds.\")
set (CMAKE_MODULE_LINKER_FLAGS_RELEASE \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during the creation of modules during RELEASE builds.\")
set (CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during the creation of modules during RELWITHDEBINFO builds.\")
set (CMAKE_MT \"CMAKE_MT-NOTFOUND\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_MT \"CMAKE_MT-NOTFOUND\" CACHE FILEPATH \"Path to a program.\")
set (CMAKE_RC_COMPILER \"rc\" CACHE FILEPATH \"RC compiler\")
set (CMAKE_RC_COMPILER \"rc\" CACHE FILEPATH \"RC compiler\")
set (CMAKE_RC_FLAGS \"-DWIN32\" CACHE STRING \"Flags for Windows Resource Compiler during all build types.\")
set (CMAKE_RC_FLAGS_DEBUG \"-D_DEBUG\" CACHE STRING \"Flags for Windows Resource Compiler during DEBUG builds.\")
set (CMAKE_SHARED_LINKER_FLAGS \"/machine:x64\" CACHE STRING \"Flags used by the linker during the creation of shared libraries during all build types.\")
set (CMAKE_SHARED_LINKER_FLAGS_DEBUG \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during the creation of shared libraries during DEBUG builds.\")
set (CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during the creation of shared libraries during MINSIZEREL builds.\")
set (CMAKE_SHARED_LINKER_FLAGS_RELEASE \"/INCREMENTAL:NO\" CACHE STRING \"Flags used by the linker during the creation of shared libraries during RELEASE builds.\")
set (CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO \"/debug /INCREMENTAL\" CACHE STRING \"Flags used by the linker during the creation of shared libraries during RELWITHDEBINFO builds.\")
set (CMAKE_SKIP_INSTALL_RPATH NO CACHE BOOL \"If set, runtime paths are not added when installing shared libraries, but are added when building.\")
set (CMAKE_SKIP_RPATH NO CACHE BOOL \"If set, runtime paths are not added when using shared libraries.\")
set (CMAKE_STATIC_LINKER_FLAGS \"/machine:x64\" CACHE STRING \"Flags used by the linker during the creation of static libraries during all build types.\")
set (CMAKE_VERBOSE_MAKEFILE FALSE CACHE BOOL \"If this value is on, makefiles will be generated without the .SILENT directive, and all commands will be echoed to the console during the make.  This is useful for debugging only. With Visual Studio IDE projects all commands are done without /nologo.\")
set (COVERAGE_COMMAND \"COVERAGE_COMMAND-NOTFOUND\" CACHE FILEPATH \"Path to the coverage program that CTest uses for performing coverage inspection\")
set (COVERAGE_EXTRA_FLAGS \"-l\" CACHE STRING \"Extra command line flags to pass to the coverage tool\")
set (CPACK_BINARY_7Z OFF CACHE BOOL \"Enable to build 7-Zip packages\")
set (CPACK_BINARY_IFW OFF CACHE BOOL \"Enable to build IFW packages\")
set (CPACK_BINARY_NSIS ON CACHE BOOL \"Enable to build NSIS packages\")
set (CPACK_BINARY_NUGET OFF CACHE BOOL \"Enable to build NuGet packages\")
set (CPACK_BINARY_WIX OFF CACHE BOOL \"Enable to build WiX packages\")
set (CPACK_BINARY_ZIP OFF CACHE BOOL \"Enable to build ZIP packages\")
set (CPACK_SOURCE_7Z ON CACHE BOOL \"Enable to build 7-Zip source packages\")
set (CPACK_SOURCE_ZIP ON CACHE BOOL \"Enable to build ZIP source packages\")
set (CTEST_SUBMIT_RETRY_COUNT \"3\" CACHE STRING \"How many times to retry timed-out CTest submissions.\")
set (CTEST_SUBMIT_RETRY_DELAY \"5\" CACHE STRING \"How long to wait between timed-out CTest submissions.\")
set (DART_TESTING_TIMEOUT \"1500\" CACHE STRING \"Maximum time allowed before CTest will kill the test.\")
set (GTest_DIR \"C:/ProgramData/Anaconda3/Library/lib/cmake/GTest\" CACHE PATH \"The directory containing a CMake configuration file for GTest.\")
set (MAKECOMMAND \"\\\"C:\\\\1rogram Files\\\\1Make\\\\1in\\\\1make.exe\\\" --build . --config \\\"\${CTEST_CONFIGURATION_TYPE}\\\"\" CACHE STRING \"Command to build the project\")
set (MEMORYCHECK_COMMAND \"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.6/bin/cuda-memcheck.exe\" CACHE FILEPATH \"Path to the memory checking command, used for memory error detection.\")
set (PRINT_UNSYMBOLIZED_STACK_TRACES OFF CACHE BOOL \"Print file offsets in traces instead of symbolizing\")
set (SITE \"Flow\" CACHE STRING \"Name of the computer/site where compile is being run\")
set (Unwind_INCLUDE_DIR \"Unwind_INCLUDE_DIR-NOTFOUND\" CACHE PATH \"unwind include directory\")
set (Unwind_LIBRARY \"Unwind_LIBRARY-NOTFOUND\" CACHE FILEPATH \"unwind library\")
set (WITH_CUSTOM_PREFIX ON CACHE BOOL \"Enable support for user-generated message prefixes\")
set (WITH_GFLAGS ON CACHE BOOL \"Use gflags\")
set (WITH_GMOCK ON CACHE BOOL \"Use Google Mock\")
set (WITH_GTEST ON CACHE BOOL \"Use Google Test\")
set (WITH_PKGCONFIG ON CACHE BOOL \"Enable pkg-config support\")
set (WITH_SYMBOLIZE ON CACHE BOOL \"Enable symbolize module\")
set (WITH_THREADS ON CACHE BOOL \"Enable multithreading support\")
set (WITH_TLS ON CACHE BOOL \"Enable Thread Local Storage (TLS) support\")
set (WITH_UNWIND ON CACHE BOOL \"Enable libunwind support\")
set (gflags_DIR \"gflags_DIR-NOTFOUND\" CACHE PATH \"The directory containing a CMake configuration file for gflags.\")
" "-P" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cmake/TestInitPackageConfig.cmake")
  set_tests_properties(cmake_package_config_init PROPERTIES  FIXTURES_SETUP "cmake_package_config" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;893;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
else()
  add_test(cmake_package_config_init NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(cmake_package_config_generate "C:/Program Files/CMake/bin/cmake.exe" "-DGENERATOR=Visual Studio 16 2019" "-DGENERATOR_PLATFORM=" "-DGENERATOR_TOOLSET=" "-DINITIAL_CACHE=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config/glog_package_config_initial_cache.cmake" "-DPACKAGE_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog" "-DPATH=C:\\ProgramData\\Anaconda3" "C:\\ProgramData\\Anaconda3\\Library\\mingw-w64\\bin" "C:\\ProgramData\\Anaconda3\\Library\\usr\\bin" "C:\\ProgramData\\Anaconda3\\Library\\bin" "C:\\ProgramData\\Anaconda3\\Scripts" "C:\\ProgramData\\Anaconda3\\bin" "C:\\ProgramData\\Anaconda3\\condabin" "C:\\Program Files\\RBTools\\bin" "C:\\ProgramData\\Oracle\\Java\\javapath" "C:\\VulkanSDK\\1.3.216.0\\Bin" "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\bin" "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\libnvvp" "C:\\Windows\\system32" "C:\\Windows" "C:\\Windows\\System32\\Wbem" "C:\\Windows\\System32\\WindowsPowerShell\\v1.0" "C:\\Windows\\System32\\OpenSSH" "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common" "C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR" "C:\\Program Files\\CMake\\bin" "C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2022.1.0" "C:\\ProgramData\\Anaconda3\\Scripts" "C:\\ProgramData\\Anaconda3" "C:\\ProgramData\\Anaconda3\\Library\\bin" "C:\\Program Files\\Go\\bin" "C:\\Program Files\\xmake" "C:\\Program Files\\Git\\cmd" "C:\\Program Files\\dotnet" "C:\\WINDOWS\\system32" "C:\\WINDOWS" "C:\\WINDOWS\\System32\\Wbem" "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0" "C:\\WINDOWS\\System32\\OpenSSH" "C:\\Users\\78204\\AppData\\Local\\Microsoft\\WindowsApps" "C:\\Program Files (x86)\\Microsoft VS Code\\bin" "C:\\Users\\78204\\go\\bin" "C:\\Users\\78204\\.dotnet\\tools" "-DSOURCE_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/src/package_config_unittest/working_config" "-DTEST_BINARY_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config/working_config" "-P" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cmake/TestPackageConfig.cmake")
  set_tests_properties(cmake_package_config_generate PROPERTIES  FIXTURES_REQUIRED "cmake_package_config" FIXTURES_SETUP "cmake_package_config_working" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;900;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(cmake_package_config_generate "C:/Program Files/CMake/bin/cmake.exe" "-DGENERATOR=Visual Studio 16 2019" "-DGENERATOR_PLATFORM=" "-DGENERATOR_TOOLSET=" "-DINITIAL_CACHE=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config/glog_package_config_initial_cache.cmake" "-DPACKAGE_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog" "-DPATH=C:\\ProgramData\\Anaconda3" "C:\\ProgramData\\Anaconda3\\Library\\mingw-w64\\bin" "C:\\ProgramData\\Anaconda3\\Library\\usr\\bin" "C:\\ProgramData\\Anaconda3\\Library\\bin" "C:\\ProgramData\\Anaconda3\\Scripts" "C:\\ProgramData\\Anaconda3\\bin" "C:\\ProgramData\\Anaconda3\\condabin" "C:\\Program Files\\RBTools\\bin" "C:\\ProgramData\\Oracle\\Java\\javapath" "C:\\VulkanSDK\\1.3.216.0\\Bin" "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\bin" "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\libnvvp" "C:\\Windows\\system32" "C:\\Windows" "C:\\Windows\\System32\\Wbem" "C:\\Windows\\System32\\WindowsPowerShell\\v1.0" "C:\\Windows\\System32\\OpenSSH" "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common" "C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR" "C:\\Program Files\\CMake\\bin" "C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2022.1.0" "C:\\ProgramData\\Anaconda3\\Scripts" "C:\\ProgramData\\Anaconda3" "C:\\ProgramData\\Anaconda3\\Library\\bin" "C:\\Program Files\\Go\\bin" "C:\\Program Files\\xmake" "C:\\Program Files\\Git\\cmd" "C:\\Program Files\\dotnet" "C:\\WINDOWS\\system32" "C:\\WINDOWS" "C:\\WINDOWS\\System32\\Wbem" "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0" "C:\\WINDOWS\\System32\\OpenSSH" "C:\\Users\\78204\\AppData\\Local\\Microsoft\\WindowsApps" "C:\\Program Files (x86)\\Microsoft VS Code\\bin" "C:\\Users\\78204\\go\\bin" "C:\\Users\\78204\\.dotnet\\tools" "-DSOURCE_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/src/package_config_unittest/working_config" "-DTEST_BINARY_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config/working_config" "-P" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cmake/TestPackageConfig.cmake")
  set_tests_properties(cmake_package_config_generate PROPERTIES  FIXTURES_REQUIRED "cmake_package_config" FIXTURES_SETUP "cmake_package_config_working" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;900;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(cmake_package_config_generate "C:/Program Files/CMake/bin/cmake.exe" "-DGENERATOR=Visual Studio 16 2019" "-DGENERATOR_PLATFORM=" "-DGENERATOR_TOOLSET=" "-DINITIAL_CACHE=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config/glog_package_config_initial_cache.cmake" "-DPACKAGE_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog" "-DPATH=C:\\ProgramData\\Anaconda3" "C:\\ProgramData\\Anaconda3\\Library\\mingw-w64\\bin" "C:\\ProgramData\\Anaconda3\\Library\\usr\\bin" "C:\\ProgramData\\Anaconda3\\Library\\bin" "C:\\ProgramData\\Anaconda3\\Scripts" "C:\\ProgramData\\Anaconda3\\bin" "C:\\ProgramData\\Anaconda3\\condabin" "C:\\Program Files\\RBTools\\bin" "C:\\ProgramData\\Oracle\\Java\\javapath" "C:\\VulkanSDK\\1.3.216.0\\Bin" "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\bin" "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\libnvvp" "C:\\Windows\\system32" "C:\\Windows" "C:\\Windows\\System32\\Wbem" "C:\\Windows\\System32\\WindowsPowerShell\\v1.0" "C:\\Windows\\System32\\OpenSSH" "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common" "C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR" "C:\\Program Files\\CMake\\bin" "C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2022.1.0" "C:\\ProgramData\\Anaconda3\\Scripts" "C:\\ProgramData\\Anaconda3" "C:\\ProgramData\\Anaconda3\\Library\\bin" "C:\\Program Files\\Go\\bin" "C:\\Program Files\\xmake" "C:\\Program Files\\Git\\cmd" "C:\\Program Files\\dotnet" "C:\\WINDOWS\\system32" "C:\\WINDOWS" "C:\\WINDOWS\\System32\\Wbem" "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0" "C:\\WINDOWS\\System32\\OpenSSH" "C:\\Users\\78204\\AppData\\Local\\Microsoft\\WindowsApps" "C:\\Program Files (x86)\\Microsoft VS Code\\bin" "C:\\Users\\78204\\go\\bin" "C:\\Users\\78204\\.dotnet\\tools" "-DSOURCE_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/src/package_config_unittest/working_config" "-DTEST_BINARY_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config/working_config" "-P" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cmake/TestPackageConfig.cmake")
  set_tests_properties(cmake_package_config_generate PROPERTIES  FIXTURES_REQUIRED "cmake_package_config" FIXTURES_SETUP "cmake_package_config_working" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;900;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(cmake_package_config_generate "C:/Program Files/CMake/bin/cmake.exe" "-DGENERATOR=Visual Studio 16 2019" "-DGENERATOR_PLATFORM=" "-DGENERATOR_TOOLSET=" "-DINITIAL_CACHE=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config/glog_package_config_initial_cache.cmake" "-DPACKAGE_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog" "-DPATH=C:\\ProgramData\\Anaconda3" "C:\\ProgramData\\Anaconda3\\Library\\mingw-w64\\bin" "C:\\ProgramData\\Anaconda3\\Library\\usr\\bin" "C:\\ProgramData\\Anaconda3\\Library\\bin" "C:\\ProgramData\\Anaconda3\\Scripts" "C:\\ProgramData\\Anaconda3\\bin" "C:\\ProgramData\\Anaconda3\\condabin" "C:\\Program Files\\RBTools\\bin" "C:\\ProgramData\\Oracle\\Java\\javapath" "C:\\VulkanSDK\\1.3.216.0\\Bin" "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\bin" "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\libnvvp" "C:\\Windows\\system32" "C:\\Windows" "C:\\Windows\\System32\\Wbem" "C:\\Windows\\System32\\WindowsPowerShell\\v1.0" "C:\\Windows\\System32\\OpenSSH" "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common" "C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR" "C:\\Program Files\\CMake\\bin" "C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2022.1.0" "C:\\ProgramData\\Anaconda3\\Scripts" "C:\\ProgramData\\Anaconda3" "C:\\ProgramData\\Anaconda3\\Library\\bin" "C:\\Program Files\\Go\\bin" "C:\\Program Files\\xmake" "C:\\Program Files\\Git\\cmd" "C:\\Program Files\\dotnet" "C:\\WINDOWS\\system32" "C:\\WINDOWS" "C:\\WINDOWS\\System32\\Wbem" "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0" "C:\\WINDOWS\\System32\\OpenSSH" "C:\\Users\\78204\\AppData\\Local\\Microsoft\\WindowsApps" "C:\\Program Files (x86)\\Microsoft VS Code\\bin" "C:\\Users\\78204\\go\\bin" "C:\\Users\\78204\\.dotnet\\tools" "-DSOURCE_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/src/package_config_unittest/working_config" "-DTEST_BINARY_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config/working_config" "-P" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cmake/TestPackageConfig.cmake")
  set_tests_properties(cmake_package_config_generate PROPERTIES  FIXTURES_REQUIRED "cmake_package_config" FIXTURES_SETUP "cmake_package_config_working" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;900;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
else()
  add_test(cmake_package_config_generate NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(cmake_package_config_build "C:/Program Files/CMake/bin/cmake.exe" "--build" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config/working_config" "--config" "Debug")
  set_tests_properties(cmake_package_config_build PROPERTIES  FIXTURES_REQUIRED "cmake_package_config;cmake_package_config_working" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;912;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(cmake_package_config_build "C:/Program Files/CMake/bin/cmake.exe" "--build" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config/working_config" "--config" "Release")
  set_tests_properties(cmake_package_config_build PROPERTIES  FIXTURES_REQUIRED "cmake_package_config;cmake_package_config_working" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;912;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(cmake_package_config_build "C:/Program Files/CMake/bin/cmake.exe" "--build" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config/working_config" "--config" "MinSizeRel")
  set_tests_properties(cmake_package_config_build PROPERTIES  FIXTURES_REQUIRED "cmake_package_config;cmake_package_config_working" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;912;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(cmake_package_config_build "C:/Program Files/CMake/bin/cmake.exe" "--build" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config/working_config" "--config" "RelWithDebInfo")
  set_tests_properties(cmake_package_config_build PROPERTIES  FIXTURES_REQUIRED "cmake_package_config;cmake_package_config_working" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;912;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
else()
  add_test(cmake_package_config_build NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(cmake_package_config_cleanup "C:/Program Files/CMake/bin/cmake.exe" "-E" "remove_directory" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config")
  set_tests_properties(cmake_package_config_cleanup PROPERTIES  FIXTURES_CLEANUP "cmake_package_config" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;917;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(cmake_package_config_cleanup "C:/Program Files/CMake/bin/cmake.exe" "-E" "remove_directory" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config")
  set_tests_properties(cmake_package_config_cleanup PROPERTIES  FIXTURES_CLEANUP "cmake_package_config" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;917;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(cmake_package_config_cleanup "C:/Program Files/CMake/bin/cmake.exe" "-E" "remove_directory" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config")
  set_tests_properties(cmake_package_config_cleanup PROPERTIES  FIXTURES_CLEANUP "cmake_package_config" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;917;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(cmake_package_config_cleanup "C:/Program Files/CMake/bin/cmake.exe" "-E" "remove_directory" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/test_package_config")
  set_tests_properties(cmake_package_config_cleanup PROPERTIES  FIXTURES_CLEANUP "cmake_package_config" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;917;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
else()
  add_test(cmake_package_config_cleanup NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(cleanup_init "C:/Program Files/CMake/bin/cmake.exe" "-E" "make_directory" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cleanup_tests")
  set_tests_properties(cleanup_init PROPERTIES  FIXTURES_SETUP "logcleanuptest" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;955;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(cleanup_init "C:/Program Files/CMake/bin/cmake.exe" "-E" "make_directory" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cleanup_tests")
  set_tests_properties(cleanup_init PROPERTIES  FIXTURES_SETUP "logcleanuptest" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;955;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(cleanup_init "C:/Program Files/CMake/bin/cmake.exe" "-E" "make_directory" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cleanup_tests")
  set_tests_properties(cleanup_init PROPERTIES  FIXTURES_SETUP "logcleanuptest" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;955;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(cleanup_init "C:/Program Files/CMake/bin/cmake.exe" "-E" "make_directory" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cleanup_tests")
  set_tests_properties(cleanup_init PROPERTIES  FIXTURES_SETUP "logcleanuptest" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;955;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
else()
  add_test(cleanup_init NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(cleanup_logdir "C:/Program Files/CMake/bin/cmake.exe" "-E" "remove_directory" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cleanup_tests")
  set_tests_properties(cleanup_logdir PROPERTIES  FIXTURES_CLEANUP "logcleanuptest" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;957;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(cleanup_logdir "C:/Program Files/CMake/bin/cmake.exe" "-E" "remove_directory" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cleanup_tests")
  set_tests_properties(cleanup_logdir PROPERTIES  FIXTURES_CLEANUP "logcleanuptest" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;957;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(cleanup_logdir "C:/Program Files/CMake/bin/cmake.exe" "-E" "remove_directory" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cleanup_tests")
  set_tests_properties(cleanup_logdir PROPERTIES  FIXTURES_CLEANUP "logcleanuptest" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;957;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(cleanup_logdir "C:/Program Files/CMake/bin/cmake.exe" "-E" "remove_directory" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cleanup_tests")
  set_tests_properties(cleanup_logdir PROPERTIES  FIXTURES_CLEANUP "logcleanuptest" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;957;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
else()
  add_test(cleanup_logdir NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(cleanup_immediately "C:/Program Files/CMake/bin/cmake.exe" "-DLOGCLEANUP=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/Debug/cleanup_immediately_unittest.exe" "-DTEST_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cleanup_tests/" "-P" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cmake/RunCleanerTest1.cmake")
  set_tests_properties(cleanup_immediately PROPERTIES  FIXTURES_REQUIRED "logcleanuptest" WORKING_DIRECTORY "C:/FlowSource/code/FlowLab/RayFlow/ext/glog" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;959;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(cleanup_immediately "C:/Program Files/CMake/bin/cmake.exe" "-DLOGCLEANUP=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/Release/cleanup_immediately_unittest.exe" "-DTEST_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cleanup_tests/" "-P" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cmake/RunCleanerTest1.cmake")
  set_tests_properties(cleanup_immediately PROPERTIES  FIXTURES_REQUIRED "logcleanuptest" WORKING_DIRECTORY "C:/FlowSource/code/FlowLab/RayFlow/ext/glog" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;959;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(cleanup_immediately "C:/Program Files/CMake/bin/cmake.exe" "-DLOGCLEANUP=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/MinSizeRel/cleanup_immediately_unittest.exe" "-DTEST_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cleanup_tests/" "-P" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cmake/RunCleanerTest1.cmake")
  set_tests_properties(cleanup_immediately PROPERTIES  FIXTURES_REQUIRED "logcleanuptest" WORKING_DIRECTORY "C:/FlowSource/code/FlowLab/RayFlow/ext/glog" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;959;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(cleanup_immediately "C:/Program Files/CMake/bin/cmake.exe" "-DLOGCLEANUP=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/RelWithDebInfo/cleanup_immediately_unittest.exe" "-DTEST_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cleanup_tests/" "-P" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cmake/RunCleanerTest1.cmake")
  set_tests_properties(cleanup_immediately PROPERTIES  FIXTURES_REQUIRED "logcleanuptest" WORKING_DIRECTORY "C:/FlowSource/code/FlowLab/RayFlow/ext/glog" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;959;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
else()
  add_test(cleanup_immediately NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(cleanup_with_absolute_prefix "C:/Program Files/CMake/bin/cmake.exe" "-DLOGCLEANUP=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/Debug/cleanup_with_absolute_prefix_unittest.exe" "-DTEST_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/" "-P" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cmake/RunCleanerTest2.cmake")
  set_tests_properties(cleanup_with_absolute_prefix PROPERTIES  FIXTURES_REQUIRED "logcleanuptest" WORKING_DIRECTORY "C:/FlowSource/code/FlowLab/RayFlow/ext/glog" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;966;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(cleanup_with_absolute_prefix "C:/Program Files/CMake/bin/cmake.exe" "-DLOGCLEANUP=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/Release/cleanup_with_absolute_prefix_unittest.exe" "-DTEST_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/" "-P" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cmake/RunCleanerTest2.cmake")
  set_tests_properties(cleanup_with_absolute_prefix PROPERTIES  FIXTURES_REQUIRED "logcleanuptest" WORKING_DIRECTORY "C:/FlowSource/code/FlowLab/RayFlow/ext/glog" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;966;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(cleanup_with_absolute_prefix "C:/Program Files/CMake/bin/cmake.exe" "-DLOGCLEANUP=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/MinSizeRel/cleanup_with_absolute_prefix_unittest.exe" "-DTEST_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/" "-P" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cmake/RunCleanerTest2.cmake")
  set_tests_properties(cleanup_with_absolute_prefix PROPERTIES  FIXTURES_REQUIRED "logcleanuptest" WORKING_DIRECTORY "C:/FlowSource/code/FlowLab/RayFlow/ext/glog" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;966;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(cleanup_with_absolute_prefix "C:/Program Files/CMake/bin/cmake.exe" "-DLOGCLEANUP=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/RelWithDebInfo/cleanup_with_absolute_prefix_unittest.exe" "-DTEST_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/" "-P" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cmake/RunCleanerTest2.cmake")
  set_tests_properties(cleanup_with_absolute_prefix PROPERTIES  FIXTURES_REQUIRED "logcleanuptest" WORKING_DIRECTORY "C:/FlowSource/code/FlowLab/RayFlow/ext/glog" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;966;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
else()
  add_test(cleanup_with_absolute_prefix NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(cleanup_with_relative_prefix "C:/Program Files/CMake/bin/cmake.exe" "-DLOGCLEANUP=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/Debug/cleanup_with_relative_prefix_unittest.exe" "-DTEST_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/" "-DTEST_SUBDIR=test_subdir/" "-P" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cmake/RunCleanerTest3.cmake")
  set_tests_properties(cleanup_with_relative_prefix PROPERTIES  FIXTURES_REQUIRED "logcleanuptest" WORKING_DIRECTORY "C:/FlowSource/code/FlowLab/RayFlow/ext/glog" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;972;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(cleanup_with_relative_prefix "C:/Program Files/CMake/bin/cmake.exe" "-DLOGCLEANUP=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/Release/cleanup_with_relative_prefix_unittest.exe" "-DTEST_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/" "-DTEST_SUBDIR=test_subdir/" "-P" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cmake/RunCleanerTest3.cmake")
  set_tests_properties(cleanup_with_relative_prefix PROPERTIES  FIXTURES_REQUIRED "logcleanuptest" WORKING_DIRECTORY "C:/FlowSource/code/FlowLab/RayFlow/ext/glog" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;972;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(cleanup_with_relative_prefix "C:/Program Files/CMake/bin/cmake.exe" "-DLOGCLEANUP=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/MinSizeRel/cleanup_with_relative_prefix_unittest.exe" "-DTEST_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/" "-DTEST_SUBDIR=test_subdir/" "-P" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cmake/RunCleanerTest3.cmake")
  set_tests_properties(cleanup_with_relative_prefix PROPERTIES  FIXTURES_REQUIRED "logcleanuptest" WORKING_DIRECTORY "C:/FlowSource/code/FlowLab/RayFlow/ext/glog" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;972;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(cleanup_with_relative_prefix "C:/Program Files/CMake/bin/cmake.exe" "-DLOGCLEANUP=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/RelWithDebInfo/cleanup_with_relative_prefix_unittest.exe" "-DTEST_DIR=C:/FlowSource/code/FlowLab/RayFlow/ext/glog/" "-DTEST_SUBDIR=test_subdir/" "-P" "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/cmake/RunCleanerTest3.cmake")
  set_tests_properties(cleanup_with_relative_prefix PROPERTIES  FIXTURES_REQUIRED "logcleanuptest" WORKING_DIRECTORY "C:/FlowSource/code/FlowLab/RayFlow/ext/glog" _BACKTRACE_TRIPLES "C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;972;add_test;C:/FlowSource/code/FlowLab/RayFlow/ext/glog/CMakeLists.txt;0;")
else()
  add_test(cleanup_with_relative_prefix NOT_AVAILABLE)
endif()
